aws dynamodb create-table --table-name wsf_songbooks --attribute-definitions AttributeName=SongbookID,AttributeType=N --key-schema AttributeName=SongbookID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songinstances_songbooks --attribute-definitions AttributeName=SongbookID,AttributeType=N AttributeName=SongInstanceIDEntryNumber,AttributeType=S --key-schema AttributeName=SongbookID,KeyType=HASH AttributeName=SongInstanceIDEntryNumber,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songinstances_artists --attribute-definitions AttributeName=ArtistID,AttributeType=N AttributeName=SongInstanceIDRole,AttributeType=S --key-schema AttributeName=ArtistID,KeyType=HASH AttributeName=SongInstanceIDRole,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_artists --attribute-definitions AttributeName=ArtistID,AttributeType=N --key-schema AttributeName=ArtistID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songinstances_tunes --attribute-definitions AttributeName=TuneID,AttributeType=N AttributeName=SongInstanceID,AttributeType=N --key-schema AttributeName=TuneID,KeyType=HASH AttributeName=SongInstanceID,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_tunes --attribute-definitions AttributeName=TuneID,AttributeType=N --key-schema AttributeName=TuneID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songinstances_keysignatures --attribute-definitions AttributeName=KeySignatureID,AttributeType=N AttributeName=SongInstanceID,AttributeType=N --key-schema AttributeName=KeySignatureID,KeyType=HASH AttributeName=SongInstanceID,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_keysignatures --attribute-definitions AttributeName=KeySignatureID,AttributeType=N --key-schema AttributeName=KeySignatureID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songinstances_timesignatures --attribute-definitions AttributeName=TimeSignatureID,AttributeType=N AttributeName=SongInstanceID,AttributeType=N --key-schema AttributeName=TimeSignatureID,KeyType=HASH AttributeName=SongInstanceID,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_timesignatures --attribute-definitions AttributeName=TimeSignatureID,AttributeType=N --key-schema AttributeName=TimeSignatureID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songinstances_meters --attribute-definitions AttributeName=MeterID,AttributeType=N AttributeName=SongInstanceID,AttributeType=N --key-schema AttributeName=MeterID,KeyType=HASH AttributeName=SongInstanceID,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_meters --attribute-definitions AttributeName=MeterID,AttributeType=N --key-schema AttributeName=MeterID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songinstances_scripturereferences --attribute-definitions AttributeName=ScriptureReferenceID,AttributeType=N AttributeName=SongInstanceID,AttributeType=N --key-schema AttributeName=ScriptureReferenceID,KeyType=HASH AttributeName=SongInstanceID,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_bible_books --attribute-definitions AttributeName=BookID,AttributeType=N --key-schema AttributeName=BookID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_scripturereferences --attribute-definitions AttributeName=ScriptureReferenceID,AttributeType=N --key-schema AttributeName=ScriptureReferenceID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songinstances_languages --attribute-definitions AttributeName=LanguageID,AttributeType=N AttributeName=SongInstanceID,AttributeType=N --key-schema AttributeName=LanguageID,KeyType=HASH AttributeName=SongInstanceID,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_languages --attribute-definitions AttributeName=LanguageID,AttributeType=N --key-schema AttributeName=LanguageID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songinstances_arrangementtypes --attribute-definitions AttributeName=ArrangementTypeID,AttributeType=N AttributeName=SongInstanceID,AttributeType=N --key-schema AttributeName=ArrangementTypeID,KeyType=HASH AttributeName=SongInstanceID,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_arrangementtypes --attribute-definitions AttributeName=ArrangementTypeID,AttributeType=N --key-schema AttributeName=ArrangementTypeID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_lyrics_first_lines --attribute-definitions AttributeName=SongInstanceID,AttributeType=N AttributeName=LyricsIDFirstLineOrder,AttributeType=S --key-schema AttributeName=SongInstanceID,KeyType=HASH AttributeName=LyricsIDFirstLineOrder,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songinstances --attribute-definitions AttributeName=SongInstanceID,AttributeType=N --key-schema AttributeName=SongInstanceID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songs_topics --attribute-definitions AttributeName=TopicID,AttributeType=N AttributeName=SongID,AttributeType=N --key-schema AttributeName=TopicID,KeyType=HASH AttributeName=SongID,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_topics --attribute-definitions AttributeName=TopicID,AttributeType=N --key-schema AttributeName=TopicID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_songs --attribute-definitions AttributeName=SongID,AttributeType=N --key-schema AttributeName=SongID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_psalmsongs_lyrics_tabs --attribute-definitions AttributeName=PsalmSongID,AttributeType=S AttributeName=LyricsOrder,AttributeType=N --key-schema AttributeName=PsalmSongID,KeyType=HASH AttributeName=LyricsOrder,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_psalmsongtypes --attribute-definitions AttributeName=PsalmSongTypeID,AttributeType=N --key-schema AttributeName=PsalmSongTypeID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_psalmsongs_alternativetunes --attribute-definitions AttributeName=PsalmSongID,AttributeType=S AttributeName=AlternativeTuneID,AttributeType=N --key-schema AttributeName=PsalmSongID,KeyType=HASH AttributeName=AlternativeTuneID,KeyType=RANGE --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
aws dynamodb create-table --table-name wsf_psalmsongs --attribute-definitions AttributeName=PsalmSongID,AttributeType=S --key-schema AttributeName=PsalmSongID,KeyType=HASH --billing-mode=PAY_PER_REQUEST --deletion-protection-enabled
